backend:
  name: git-gateway
  branch: master
  repo: zira-dev/website
  identity_url: "https://zira.us/.netlify/identity"
  gateway_url: "https://zira.us/.netlify/git"
  squash_merges: true

publish_mode: editorial_workflow
media_folder: "assets/img/uploads"

site_url: https://zira.us
logo_url: https://zira.us/uploads/logo.svg
collections:
  - name: 'blog'
    create: true
    label: 'Blog'
    folder: '_posts/'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
