# admin things
backend:
  name: git-gateway
  branch: master
  identity_url: "https://website.zira.us/.netlify/identity"
  gateway_url: "https://website.zira.us/.netlify/git"
  squash_merges: true

publish_mode: editorial_workflow
media_folder: "assets/img/uploads"

site_url: https://website.zira.us
logo_url: https://website.zira.us/uploads/logo.svg
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }